[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"


[functions]
  external_node_modules = ["express", "pg"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/ai/analyze"
  status = 200
  to = "/.netlify/functions/analyze"

[[redirects]]
  from = "/api/quiz/latest"
  status = 200
  to = "/.netlify/functions/quiz-latest"

[[redirects]]
  from = "/api/quiz"
  status = 200
  to = "/.netlify/functions/quiz-save"

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

# SPA fallback so client routes work on refresh
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
